
version: '3.0'

services:
  main:
    container_name: etp_backend
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 5010:5010
      - 5011:5011
    restart: always