
import { ISampNew, IStag } from "../../../models/ISamp"


export const Stags: IStag[] = [
  {
    "kp_stage_guid": "0050569CDC861EED87DD0FCCDBEAA08C",
    "kp_sample_guid": "0050569CDC861EED87DD0FCCDBEA808C",
    "opr_usl_stage_id": "7",
    "opr_usl_stage": "ПриобретениеАЗСиземли ___LOCAL",
    "opr_usl_stage_num": 1,
    isNoNds: false,
    stagSumm: "",
    stagSumm_nds: "",
    "units": [
      {
        "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEAC08C",
        "kp_stage_guid": "0050569CDC861EED87DD0FCCDBEAA08C",
        "opr_usl_unit_id": "28",
        "usl_quan_unit": "OBJ",
        "opr_usl_unit": "Стоимость земельного участка Loc",
        "nsu_menge": "0.000",
        "vat_rate": "",
        "opr_usl_unit_restr_quan": "",
        "opr_usl_unit_restr_menge": "",
        "usrps": [
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEAC08C",
            "link_id": "0050569CDC861EDD87F2DE202ED7AFAB",
            "prices_user": "0.00",
            "usl_quan_unit": "OBJ",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          },
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEAC08C",
            "link_id": "0050569CDC861EDD87F2DC5C6EC0CFA1",
            "prices_user": "0.00",
            "usl_quan_unit": "OBJ",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          }
        ]
      }
    ]
  },
  {
    "kp_stage_guid": "0050569CDC861EED87DD0FCCDBEAE08C",
    "kp_sample_guid": "0050569CDC861EED87DD0FCCDBEA808C",
    "opr_usl_stage_id": "11",
    "opr_usl_stage": "Арендаземли",
    "opr_usl_stage_num": 2,
    isNoNds: false,
    stagSumm: "",
    stagSumm_nds: "",
    "units": [
      {
        "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB008C",
        "kp_stage_guid": "0050569CDC861EED87DD0FCCDBEAE08C",
        "opr_usl_unit_id": "68",
        "usl_quan_unit": "HAR",
        "opr_usl_unit": "Стоимость права аренды земельного участка HAR",
        "nsu_menge": "0.000",
        "vat_rate": "",
        "opr_usl_unit_restr_quan": "",
        "opr_usl_unit_restr_menge": "",
        "usrps": [
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB008C",
            "link_id": "0050569CDC861EDD87F2DE202ED7AFAB",
            "prices_user": "0.00",
            "usl_quan_unit": "HAR",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          },
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB008C",
            "link_id": "0050569CDC861EDD87F2DC5C6EC0CFA1",
            "prices_user": "0.00",
            "usl_quan_unit": "HAR",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          }
        ]
      },
      {
        "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB208C",
        "kp_stage_guid": "0050569CDC861EED87DD0FCCDBEAE08C",
        "opr_usl_unit_id": "68",
        "usl_quan_unit": "SRV",
        "opr_usl_unit": "Стоимость права аренды земельного участка SRV",
        "nsu_menge": "0.000",
        "vat_rate": "",
        "opr_usl_unit_restr_quan": "",
        "opr_usl_unit_restr_menge": "",
        "usrps": [
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB208C",
            "link_id": "0050569CDC861EDD87F2DE202ED7AFAB",
            "prices_user": "0.00",
            "usl_quan_unit": "SRV",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          },
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB208C",
            "link_id": "0050569CDC861EDD87F2DC5C6EC0CFA1",
            "prices_user": "0.00",
            "usl_quan_unit": "SRV",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          }
        ]
      },
      {
        "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB408C",
        "kp_stage_guid": "0050569CDC861EED87DD0FCCDBEAE08C",
        "opr_usl_unit_id": "68",
        "usl_quan_unit": "TAG",
        "opr_usl_unit": "Стоимость права аренды земельного участка TAG",
        "nsu_menge": "0.000",
        "vat_rate": "",
        "opr_usl_unit_restr_quan": "",
        "opr_usl_unit_restr_menge": "",
        "usrps": [
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB408C",
            "link_id": "0050569CDC861EDD87F2DE202ED7AFAB",
            "prices_user": "0.00",
            "usl_quan_unit": "TAG",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          },
          {
            "kp_unit_guid": "0050569CDC861EED87DD0FCCDBEB408C",
            "link_id": "0050569CDC861EDD87F2DC5C6EC0CFA1",
            "prices_user": "0.00",
            "usl_quan_unit": "TAG",
            "nsu_menge": "0.000",
            "vat_rate": "",
            "alt_name_unit": "",
            "kp_usrp_guid": "",
            "nds_comm": "22.08.2022",
            isSubToggle: false,
            summ: "",
            summ_nds: "",
            isValid: true,
            price_date: "",
            price_time: "",
          }
        ]
      }
    ]
  },
]


export const initialState: ISampNew = {
  "kp_sample_guid": "0050569CDC861EED87DD0FCCDBEA808C",
  "link": "0050569CDC861EDD87F2DC5C6EC0CFA1",
  "konkurs_id": "_____100000037153",
  "konkurs_name": "Аренда недвижимости ____LOCAL",
  "lot_id": "100000037154",
  "lot_name": "Аренда недвижимости",
  "waers": "RUB",
  "kp_accep_date": "2022-08-18",
  "kp_send_date": "2022-08-10",
  "usl_period_end": "2022-08-10",
  "links": {
    "link": "0050569CDC861EDD87F2DC5C6EC0CFA1",
    "info_ka_email": "test@adsdddd.com",
    "info_ka_name": "Петр Петров Петрович",
    "kp_offer_expire_date": "2022-08-10",// null,
    "travel_exp": "1.00",
    "travel_exp_comm": "тест",

    kp_sample_guid: "0050569CDC861EED87DD0FCCDBEA808C"
  },
  "stags": Stags,

  kp_summ: "",
  kp_summ_nds: "",
  isTravel: false,
}